services:
  mysql-db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: meinpasswort
      MYSQL_DATABASE: platzhalter
    networks:
      - backend-database-net
    volumes:
      - mysql-example-data2:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 5s
      retries: 10

  backend:
    build: .
    ports: 
    - "3000:3000"
    networks:
      - backend-database-net
      - backend-frontend-net
    depends_on:
      mysql-db:
        condition: service_healthy

  frontend:
    build: ./frontendOrdner
    ports: 
    - "8080:80"
    networks:
      - backend-frontend-net

networks:
  backend-database-net:
    driver: bridge
  backend-frontend-net:
    driver: bridge

volumes:
  mysql-example-data2: